<?php

beforeEach(function () {
    $this->subject = new \App\Http\Requests\Auth\LoginRequest();
});

test('authorize', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->authorize();

    $this->assertTrue($actual);
});

test('rules', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $actual = $this->subject->rules();

    $this->assertValidationRules([
        'email' => [
            'required',
            'string',
            'email',
        ],
        'password' => [
            'required',
            'string',
        ],
    ], $actual);
});

// test cases...
