<?php

test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $block = \App\Models\Block::factory()->create();

    $response = $this->get(route('block', [$block]));

    $response->assertOk();
    $response->assertViewIs('pages.block');
    $response->assertViewHas('block', $block);
    $response->assertViewHas('transactions');

    // TODO: perform additional assertions
});

// test cases...
