<?php

test('mining yield calculator returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('calculator.mining'));

    $response->assertOk();
    $response->assertViewIs('pages.calculators.mining');
    $response->assertViewHas('price');
    $response->assertViewHas('hashrate');
    $response->assertViewHas('difficulty');

    // TODO: perform additional assertions
});

test('witness yield calculator returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('calculator.witness'));

    $response->assertOk();
    $response->assertViewIs('pages.calculators.witness');
    $response->assertViewHas('networkWeight');
    $response->assertViewHas('networkWeightAdjusted');
    $response->assertViewHas('witnessReward');

    // TODO: perform additional assertions
});

// test cases...
