<?php

test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('home'));

    $response->assertOk();
    $response->assertViewIs('pages.home');
    $response->assertViewHas('blocks');
    $response->assertViewHas('blockHeight');
    $response->assertViewHas('hashrate');
    $response->assertViewHas('difficulty');
    $response->assertViewHas('transactions24hr');
    $response->assertViewHas('price');

    // TODO: perform additional assertions
});

// test cases...
