<?php

test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('node-information'));

    $response->assertOk();
    $response->assertViewIs('pages.node-information');
    $response->assertViewHas('running');

    // TODO: perform additional assertions
});

// test cases...
