<?php

test('create returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->get(route('login'));

    $response->assertOk();
    $response->assertViewIs('auth.login');

    // TODO: perform additional assertions
});

test('destroy returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $user = \App\Models\User::factory()->create();

    $response = $this->actingAs($user)->post(route('logout'), [
        // TODO: send request data
    ]);

    $response->assertRedirect('/');

    // TODO: perform additional assertions
});

test('store returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->post('login', [
        // TODO: send request data
    ]);

    $response->assertRedirect(intended(RouteServiceProvider::HOME));

    // TODO: perform additional assertions
});

test('store validates with a form request', function () {
    $this->assertActionUsesFormRequest(
        \App\Http\Controllers\Auth\AuthenticatedSessionController::class,
        'store',
        \App\Http\Requests\Auth\LoginRequest::class
    );
});

// test cases...
