<?php

test('invoke returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $response = $this->getJson('api/nonce-distribution');

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

// test cases...
