<?php

test('index returns an ok response', function () {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $price = \App\Models\Price::factory()->create();

    $response = $this->getJson('api/prices/{timeframe}');

    $response->assertOk();
    $response->assertJsonStructure([
        // TODO: compare expected response data
    ]);

    // TODO: perform additional assertions
});

// test cases...
